### PR TITLE
support MMLongBench-Doc

### PR DESCRIPTION
**Pull request by mayubo2333**
Currently only three open-source models are supported for the evaluation of MMLongBench-Doc: 'MiniCPM-Llama3-V-2_5', 'InternVL-Chat-V1-5', 'XComposer2_4KHD'. More open-source models will be supported.

### CODE REVIEW

**Comment by mayubo2333** [comment]
Hi, anything I can do for resolving this conflict?

**Comment by kennymckormick** [comment]
@mayubo2333 Hi, @junming-yang is working on resolving the conflicts

**Comment by mayubo2333** [comment]
Got it, thanks for your hard work!

**Comment by junming-yang** [comment]
Hi, @mayubo2333. We have refactored this PR in a new [PR 276](https://github.com/open-compass/VLMEvalKit/pull/276). Can you help review it?

**Comment by mayubo2333** [comment]
Hi @junming-yang , thanks for your refactoring, no problem! I will review the code soon.

**Comment by junming-yang** [comment]
Have done in [PR 278](https://github.com/open-compass/VLMEvalKit/pull/278).

**Pull request closed without merging**
