### PR TITLE
[Model] add kosmos2

### PR DESCRIPTION
**Pull request by tackhwa**
- tested on `MME` dataset
c575b731fb648d324a4f1e511bd4080

`observation`: It seems that Kosmos2 does not pre-train well with strong knowledge, resulting in poor performance on datasets that require extensive knowledge (testes with MMBench, overall only get 0.013), but it performance is as expected while testing on other dataset which do not require as much knowledge:

- `BLINK` dataset
image

- `LLavaBench`
image

- `MMMU`
image

- `MMStar`
image

- `MMVet`
image

### CODE REVIEW

**Review by kennymckormick — APPROVED** [review]

**Comment by tackhwa** [comment]
@kennymckormick the conflict is fixed, and this pr is ready for merge, please feel free to take your time to review this pr, thank you, appreciate.

**Comment by Myhs-phz** [comment]
@tackhwa I evaluated kosmos2 based on datasets adopted here. However, there is a significant difference in the results of LLaVABunch and MMVet. Which judge model did you choose when implementing evaluation?

**Comment by Myhs-phz** [comment]
@tackhwa I evaluated kosmos2 based on datasets adopted here. However, there is a significant difference in the results of LLaVABunch and MMVet. Which judge model did you choose when implementing evaluation?

**Comment by tackhwa** [comment]
> @tackhwa I evaluated kosmos2 based on datasets adopted here. However, there is a significant difference in the results of LLaVABunch and MMVet. Which judge model did you choose when implementing evaluation?

I modify the source code and use free api of `internlm2_5-7b-chat` that available in [SiliconFlow](https://siliconflow.cn/), so the result might be different, may i know what accuarcy you get?

**Comment by Myhs-phz** [comment]
@tackhwa I use the api of ### gpt-4-1106-preview

**Comment by Myhs-phz** [comment]
@tackhwa  I use the api of gpt-4-1106-preview. Here are evaluation results i get.

- LLaVABench
img_v3_02fo_a57d4807-382d-4e71-909d-15de94a7ff8g

- MMMU
img_v3_02fo_3dace5a5-b548-48ce-b987-4225cf6e1b5g

- MMVet
img_v3_02fo_9fd6f5a1-70a9-4d6a-8bfa-c042778facag

**Pull request merged**
