### PR TITLE
[Model] RBDash Added

### PR DESCRIPTION
**Pull request by anzhao920**
Adding RBDash model

Details :

RBDash GitHub repository: https://github.com/RBDash-Team/RBDash
RBDash model: https://huggingface.co/RBDash-Team/RBDash-v1.2-72b

### CODE REVIEW

**Comment by anzhao920** [comment]
> @anzhao920 Thank you for your contribution, I was wondering if you forgot to use the variable `options` in the `build_mme` and `build_hallusionbench` functions under the rbdash.py file and if it needs to be added to the prompt. If not, I will consider removing this variable.

Thank you so much for your reply. I've removed these unused variables. PTAL.

**Comment by FangXinyu-0913** [comment]
https://huggingface.co/RBDash-Team/RBDash-v1.2-72b This page is 404, where can the model weight be downloaded?

**Comment by anzhao920** [comment]
> https://huggingface.co/RBDash-Team/RBDash-v1.2-72b This page is 404, where can the model weight be downloaded?

@FangXinyu-0913 My apologies for not making the Hugging Face model public earlier. It is now available for download. Please try the link again: https://huggingface.co/RBDash-Team/RBDash-v1.2-72b.

**Comment by FangXinyu-0913** [comment]
image
I encountered this problem when loading, but the repository you provided(https://huggingface.co/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup) does not contain the file preprocessor_config.json, and I would like to ask which repository should I go to download it.

**Comment by anzhao920** [comment]
> image I encountered this problem when loading, but the repository you provided(https://huggingface.co/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup) does not contain the file preprocessor_config.json, and I would like to ask which repository should I go to download it.

@FangXinyu-0913 The preprocessing configuration for the model (OpenCLIP-ConvNeXt-L) we are using is consistent with clip-vit-large-patch14-336. Please use the configuration available at: https://huggingface.co/openai/clip-vit-large-patch14-336/blob/main/preprocessor_config.json.

Apologies for the previous issues in our official RBDash README. The vision encoder used for this model is actually InternViT-6B-448px-V1-5 rather than clip-vit-large-patch14-336. The README has now been updated accordingly, and you can find the details here: https://github.com/RBDash-Team/RBDash?tab=readme-ov-file#pretrained-weights.

**Comment by FangXinyu-0913** [comment]
image
@anzhao920 Thank you for your answer. I'm experiencing this problem when loading models. It looks like it's due to the lack of video memory that makes it difficult to fully load the model onto the GPU, and I wanted to ask if there is a way to spread the model weights evenly across the GPUs (like the `automodel.from_pretrained` function that sets the device_map parameter) so that I can make sure that the model is loading correctly.

**Comment by anzhao920** [comment]
> image @anzhao920 Thank you for your answer. I'm experiencing this problem when loading models. It looks like it's due to the lack of memory that makes it difficult to load the model onto the GPU fully, and I wanted to ask if there is a way to spread the model weights evenly across the GPUs (like the `automodel.from_pretrained` function that sets the device_map parameter) so that I can make sure that the model is loading correctly.

@FangXinyu-0913 Setting 'device_map' to 'auto' when loading the model should be sufficient.

**Comment by FangXinyu-0913** [comment]
I added `device_map='auto'`, but still encountered OOM, so I also add `device='cpu'`. This allowed the model to load successfully, but it was slow, and ran into this problem. What do you think could be done to fix it?
image

**Comment by anzhao920** [comment]
> I added `device_map='auto'`, but still encountered OOM, so I also add `device='cpu'`. This allowed the model to load successfully, but it was slow, and ran into this problem. What do you think could be done to fix it? image

@FangXinyu-0913 Could you please provide the type of GPU you use for testing and the number of GPUs you test with? We plan to replicate the setup locally and will submit it once we've confirmed it works.

**Comment by FangXinyu-0913** [comment]
> > I added `device_map='auto'`, but still encountered OOM, so I also add `device='cpu'`. This allowed the model to load successfully, but it was slow, and ran into this problem. What do you think could be done to fix it? image
> 
> @FangXinyu-0913 Could you please provide the type of GPU you use for testing and the number of GPUs you test with? We plan to replicate the setup locally and will submit it once we've confirmed it works.

NVIDIA A800-SXM4-80GB * 2. Thanks for your help!

**Comment by FangXinyu-0913** [comment]
Thank you for your reply! I have successfully loaded the model on 4 A800 and will be merging this PR within the day. If you have any comments for further changes, feel free to submit a commit or comment.

**Comment by FangXinyu-0913** [comment]
eval result on MMBench_EN:
image

**Comment by anzhao920** [comment]
> eval result on MMBench_EN: image

@FangXinyu-0913 Hi Xinyu, 

I have a question regarding the performance of our model on the OpenCompass multi-modal leaderboard. According to the leaderboard, our model’s score on MMBench is 80.2. However, the figure you provided shows a score of 83.1.

Could you please help clarify the reason for this discrepancy? Thank you!

leaderboard

**Comment by kennymckormick** [comment]
> > eval result on MMBench_EN: image
> 
> @FangXinyu-0913 Hi Xinyu,
> 
> I have a question regarding the performance of our model on the OpenCompass multi-modal leaderboard. According to the leaderboard, our model’s score on MMBench is 80.2. However, the figure you provided shows a score of 83.1.
> 
> Could you please help clarify the reason for this discrepancy? Thank you!
> 
> leaderboard

Hi, @anzhao920 ,
On the leaderboard we present the average score of MMBench_V1.1_EN_TEST and MMBench_V1.1_CN_TEST, while the screen shot @FangXinyu-0913 provided is for MMBench_V1.0_EN_TEST.

**Comment by anzhao920** [comment]
> > > eval result on MMBench_EN: image
> > 
> > 
> > @FangXinyu-0913 Hi Xinyu,
> > I have a question regarding the performance of our model on the OpenCompass multi-modal leaderboard. According to the leaderboard, our model’s score on MMBench is 80.2. However, the figure you provided shows a score of 83.1.
> > Could you please help clarify the reason for this discrepancy? Thank you!
> > leaderboard
> 
> Hi, @anzhao920 , On the leaderboard we present the average score of MMBench_V1.1_EN_TEST and MMBench_V1.1_CN_TEST, while the screen shot @FangXinyu-0913 provided is for MMBench_V1.0_EN_TEST.

Hi, @kennymckormick Thank you very much for the clarification!

**Pull request merged**
