### PR TITLE
[Model] Update Molmo Eval to Match Official Implementation

### PR DESCRIPTION
**Pull request by jamespark3922**
**Changes**:
- Process up to max 36 crops per image instead of 12 crops in default setting.
- Integrate prompts from the official Molmo implementation to match the reported numbers in the paper. (https://molmo.allenai.org/paper.pdf).

### CODE REVIEW

**Comment by jamespark3922** [comment]
@kennymckormick  Could you take a look at this PR?

**Comment by kennymckormick** [comment]
Hi, @jamespark3922 , 
Will merge this PR after validating the implementation with 1 model.

**Review by kennymckormick — APPROVED** [review]

**Comment by kennymckormick** [comment]
- [ ] TODO: Re-evaluate Molmo Series

**Comment by kennymckormick** [comment]
Hi, @jamespark3922 , 
I find that when using this piece of codes for evaluation, the scores of Molmo-7B-O and Molmo-7B-D on MMVet dropped by around 10% (absolute). Would you please evaluate these two models on MMVet to double check?

**Pull request merged**
