### PR TITLE
[Benchmark] Support WorldMedQA-V

### PR DESCRIPTION
**Pull request by kennymckormick**
For issue #525

### CODE REVIEW

**Comment by kennymckormick** [comment]
Performance Number for GPT4o-MINI on WorldMedQA-V: 

| Original Lang  | Brazil | Israel | Japan | Spain |
| -------------- | ------ | ------ | ----- | ----- |
| VLMEvalKit     | 61.8   | 37.1   | 76.2  | 65.6  |
| Paper          | 58.4   | 37.3   | 73.2  | 64.0  |
| EN Translation | Brazil | Israel | Japan | Spain |
| VLMEvalKit     | 52.8   | 45.7   | 66.7  | 66.4  |
| Paper          | 58.4   | 43.8   | 61.3  | 63.2  |

**Comment by shan23chen** [comment]
> @shan23chen
> 
> 
> 
> Please help check the results.

Looks great! Thanks so much!

**Comment by lxasqjc** [comment]
@shan23chen @kennymckormick Thank you both for sharing your work, may I ask if those results have used the API models as a judge? if so which one? Many thanks!

**Comment by shan23chen** [comment]
we used gpt4o as judge!

**Comment by lxasqjc** [comment]
Thank you @shan23chen! 

Another question, the latest official vlmeVALKiT is using this .tsv
`'WorldMedQA-V': 'https://opencompass.openxlab.space/utils/VLMEval/WorldMedQA-V.tsv',`

While in the 'WorldMedQA/VLMEvalKit/blob/main/vlmeval/dataset/image_mcq.py' the following is used.
Is the 'WorldMedQA-V' under the official wrapup of all 4+1 languages and returns the overall average?

>         # WorldMultimodalMedQA EN version
>         'brazil_english': 'https://huggingface.co/datasets/WorldMedQA/v3/resolve/maisn/brazil_english_processed.tsv',
>         'japan_english': 'https://huggingface.co/datasets/WorldMedQA/v3/resolve/main/japan_english_processed.tsv',
>         'israel_english': 'https://huggingface.co/datasets/WorldMedQA/v3/resolve/main/israel_english_processed.tsv',
>         'spain_english': 'https://huggingface.co/datasets/WorldMedQA/v3/resolve/main/spain_english_processed.tsv',
>         
>         # WorldMultimodalMedQA Local version
>         'brazil_local': 'https://huggingface.co/datasets/WorldMedQA/v3/resolve/main/brazil_local_processed.tsv',
>         'japan_local': 'https://huggingface.co/datasets/WorldMedQA/v3/resolve/main/japan_local_processed.tsv', 
>         'israel_local': 'https://huggingface.co/datasets/WorldMedQA/v3/resolve/main/israel_local_processed.tsv',
>         'spain_local': 'https://huggingface.co/datasets/WorldMedQA/v3/resolve/main/spain_local_processed.tsv',

**Pull request merged**
