### PR TITLE
Measuring Quantitative Spatial Reasoning with the Q-Spatial Bench🔥

### PR DESCRIPTION
**Pull request by andrewliao11**
[[🔗 Homepage](https://andrewliao11.github.io/spatial_prompt/)] [[🤗 Huggingface Dataset](https://huggingface.co/datasets/andrewliao11/Q-Spatial-Bench)] [[📝 ArXiv Paper](https://web3.arxiv.org/abs/2409.09788)]

# Introduction

Despite recent advances demonstrating vision-language models' (VLMs) abilities to describe complex relationships in images using natural language, their capability to quantitatively reason about object sizes and distances remains underexplored. In this work, we introduce a manually annotated benchmark, Q-Spatial Bench, with 271 questions across five categories designed for quantitative spatial reasoning and systematically investigate the performance of state-of-the-art VLMs on this task.

# Evaluation

```bash
# Q-Spatial Bench (split: Q-Spatial ++)
torchrun --nproc-per-node=1  run.py --data QSpatial_plus --model your_model --verbose --judge gpt-4o

# Q-Spatial Bench (split: Q-Spatial ScanNet)
# Q-Spatial ScanNet requires users to get the permission from ScanNet and download using the provided helper script
torchrun --nproc-per-node=1  run.py --data QSpatial_scannet --model your_model --verbose --judge gpt-4o
```

### CODE REVIEW

**Comment by kennymckormick** [comment]
Hi, @andrewliao11 , 
Can you provide some reference performance numbers? When I try evaluate GPT-4o-2024-08-06 w. this code, GPT-4o keeps output `I'm unable to provide precise measurements from a 2D image. However, XXXXXXXXX. For an
accurate measurement, a physical measurement would be necessary.`, and the performance number I got is close to 0.

**Comment by andrewliao11** [comment]
Hey thanks for the quick reply!

I changed the default prompt scheme and here are the performance numbers and associated commands:

- Performance table

|                 | Q-Spatial-ScanNet |            |                               | Q-Spatial++ |            |                               |
|-----------------|------------------:|-----------:|------------------------------:|------------:|-----------:|------------------------------:|
|                 |             GPT4o | GPT4o_MINI | Llama-3.2-11B-Vision-Instruct |       GPT4o | GPT4o_MINI | Llama-3.2-11B-Vision-Instruct |
| Acc ($delta_2$) |             35.29 |      32.35 |                          30.5 |        61.3 |      42.57 |                         38.61 |



- Commands
```
python run.py --data {QSpatial_plus, QSpatial_scannet} --model {GPT4o, GPT4o_MINI, Llama-3.2-11B-Vision-Instruct} --mode all --judge gpt-4o-mini --work-dir vlmevalkit_qspatial/{qspatial_plus, qspatial_scannet}
```

**Comment by kennymckormick** [comment]
Hi, @andrewliao11 , 
I still encountered some issues with the latest codes:
1. When evaluating QSpatial_scannet, it says:
image

2. I can successfully evaluate QSpatial_plus. However, the results do not align with the numbers you reported:
Acc (delta2): 
GPT4o_20240809: 55.4
GPT4o_MINI: 21.8
Llama-3.2-11B: 0 

Would you please double check if the codes in this PR can reproduce the result and provide the evaluation records to me?

**Comment by kennymckormick** [comment]
> Hi, @andrewliao11 , I still encountered some issues with the latest codes:
> 
> 1. When evaluating QSpatial_scannet, it says:
>    image
> 2. I can successfully evaluate QSpatial_plus. However, the results do not align with the numbers you reported:
>    Acc (delta2):
>    GPT4o_20240809: 55.4
>    GPT4o_MINI: 21.8
>    Llama-3.2-11B: 0
> 
> Would you please double check if the codes in this PR can reproduce the result and provide the evaluation records to me?

Hi, @andrewliao11 , 
If there is no further comments, I'm going to firstly merge this PR. You can raise issues or create another PR if there needs some updates.

**Pull request merged**
