### PR TITLE
[Benchmark] Add New Datasets: Mia-Bench, OlympiadBench, and VizWiz

### PR DESCRIPTION
**Pull request by Myhs-phz**
###
Currently, the VizWiz are still awaiting updates.

### CODE REVIEW

**Comment by wdp-007** [comment]
Hello, first of all, thank you very much for your work! I noticed that the amount of data you added to OlympiadBench is only 6,765, which is different from the number in the paper (8,476). Could you please explain where this difference in quantity comes from?

**Comment by Myhs-phz** [comment]
Hello. The data that has not been included does not have a final answer. The article evaluates these data using subjective methods. We will soon supplement these data, but the objective evaluation score will not consider this part.










At 2024-12-15 00:32:21, "wangpeng" ***@***.***> wrote:

Hello, first of all, thank you very much for your work! I noticed that the amount of data you added to OlympiadBench is only 6,765, which is different from the number in the paper (8,476). Could you please explain where this difference in quantity comes from?

**Comment by wdp-007** [comment]
感谢回复！想问下如果只考虑客观题的话能跟原始论文里的结果对齐么？

**Comment by Myhs-phz** [comment]
Based on the objective question section, we used some of the models mentioned in the article for evaluation, and the results are consistent with those in the article.










在 2024-12-15 13:41:49，"wangpeng" ***@***.***> 写道：

感谢回复！想问下如果只考虑客观题的话能跟原始论文里的结果对齐么？

**Pull request closed without merging**
