### PR TITLE
support MMLongBench for xcomposer2d5

### PR DESCRIPTION
**Pull request by mayubo2333**

### CODE REVIEW

**Comment by kennymckormick** [comment]
Hi, @mayubo2333, I think we should add a workaround when the font downloading fails (for example, when the Internet is not available). For example, using the system default font.

**Comment by mayubo2333** [comment]
@kennymckormick Thanks for your reminder, let me add it.

**Comment by mayubo2333** [comment]
Hi @kennymckormick , add the workaround. Can you please check again?

**Review by kennymckormick — APPROVED** [review]

**Comment by kennymckormick** [comment]
Good now.

**Pull request merged**
