### PR TITLE
Add Support for Video-MME

### PR DESCRIPTION
**Pull request by dirkiedai**
This pull request adds support for the [Video-MME](https://video-mme.github.io/) dataset to enhance video understanding capabilities within the project. We have passed all the pre-commit tests.

### CODE REVIEW

**Comment by czczup** [comment]
I have tested this PR, and it works as expected. Looking forward to its official merge.

**Comment by kennymckormick** [comment]
> I have tested this PR, and it works as expected. Looking forward to its official merge.

@FangXinyu-0913 is working on reviewing it. We will try to merge it in this week.

**Comment by mary-0830** [comment]
hi, If I download the Video-MME dataset offline and prefer not to download it using get_cache_path(), how should I manage and load this dataset later?

**Comment by kennymckormick** [comment]
@FangXinyu-0913

**Comment by FangXinyu-0913** [comment]
> hi, If I download the Video-MME dataset offline and prefer not to download it using get_cache_path(), how should I manage and load this dataset later?

You can directly set cache_path and dataset_path to your Video-MME dataset root path (https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/dataset/videomme.py#L141 ), so the later operation will do based on your setting directory.
Or you can modify code like this
```
existing_dataset_path = '/path/to/existing/dataset'
cache_path = get_cache_path(repo_id)
if cache_path is not None and check_integrity(cache_path):
    dataset_path = cache_path
else:
    dataset_path = existing_dataset_path
    ....
    unzip_hf_zip(dataset_path)
    generate_tsv(dataset_path)
```

**Comment by mary-0830** [comment]
> > hi, If I download the Video-MME dataset offline and prefer not to download it using get_cache_path(), how should I manage and load this dataset later?
> 
> You can directly set cache_path and dataset_path to your Video-MME dataset root path (https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/dataset/videomme.py#L141 ), so the later operation will do based on your setting directory. Or you can modify code like this
> 
> ```
> existing_dataset_path = '/path/to/existing/dataset'
> cache_path = get_cache_path(repo_id)
> if cache_path is not None and check_integrity(cache_path):
>     dataset_path = cache_path
> else:
>     dataset_path = existing_dataset_path
>     ....
>     unzip_hf_zip(dataset_path)
>     generate_tsv(dataset_path)
> ```

okay! Thanks your reply. And I encounter another question, "[h264 @ 0x8989980] mmco: unref short failure"
image

**Comment by FangXinyu-0913** [comment]
> > > hi, If I download the Video-MME dataset offline and prefer not to download it using get_cache_path(), how should I manage and load this dataset later?
> > 
> > 
> > You can directly set cache_path and dataset_path to your Video-MME dataset root path (https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/dataset/videomme.py#L141 ), so the later operation will do based on your setting directory. Or you can modify code like this
> > ```
> > existing_dataset_path = '/path/to/existing/dataset'
> > cache_path = get_cache_path(repo_id)
> > if cache_path is not None and check_integrity(cache_path):
> >     dataset_path = cache_path
> > else:
> >     dataset_path = existing_dataset_path
> >     ....
> >     unzip_hf_zip(dataset_path)
> >     generate_tsv(dataset_path)
> > ```
> 
> okay! Thanks your reply. And I encounter another question, "[h264 @ 0x8989980] mmco: unref short failure" image

The error message "[h264 @ 0x8989980] mmco: unref short failure" typically occurs when using the FFmpeg library or similar tools for decoding video content. If not other exception was raised after this log, you can ignore it.

**Comment by mary-0830** [comment]
> > > > hi, If I download the Video-MME dataset offline and prefer not to download it using get_cache_path(), how should I manage and load this dataset later?
> > > 
> > > 
> > > You can directly set cache_path and dataset_path to your Video-MME dataset root path (https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/dataset/videomme.py#L141 ), so the later operation will do based on your setting directory. Or you can modify code like this
> > > ```
> > > existing_dataset_path = '/path/to/existing/dataset'
> > > cache_path = get_cache_path(repo_id)
> > > if cache_path is not None and check_integrity(cache_path):
> > >     dataset_path = cache_path
> > > else:
> > >     dataset_path = existing_dataset_path
> > >     ....
> > >     unzip_hf_zip(dataset_path)
> > >     generate_tsv(dataset_path)
> > > ```
> > 
> > 
> > okay! Thanks your reply. And I encounter another question, "[h264 @ 0x8989980] mmco: unref short failure" image
> 
> The error message "[h264 @ 0x8989980] mmco: unref short failure" typically occurs when using the FFmpeg library or similar tools for decoding video content. If no other exception information was raised after this log, you can ignore it.

And another question, there are two mode, use-subtitle and without use-subtitle. If I wanna the two score, I need to run twice, can you fix the question?

**Pull request merged**
