### PR TITLE
Add the Mantis Model to the support model list

### PR DESCRIPTION
**Pull request by BrenchCC**
As the title suggests, this pr is to add the [Mantis](https://arxiv.org/abs/2405.01483) model to the supported model list.

Supported Models:
The implementation supports 6 Mantis model from the [Mantis huggingface collection](https://huggingface.co/collections/TIGER-Lab/mantis-6619b0834594c878cdb1d6e4)

### CODE REVIEW

**Comment by junming-yang** [comment]
Hi, @BrenchCC. Have you tested `Mantis-8B-Idefics2` and `Mantis-8B-Fuyu`? The output seems to be unnormal.

**Comment by BrenchCC** [comment]
I have only test an easy output to use  Mantis-8B-Idefics2 and Mantis-8B-Fuyu. I just test SIglip and clip.

**Comment by BrenchCC** [comment]
You can refer to these two codes for reconstruction, or I will update and test them after a while.
[https://github.com/TIGER-AI-Lab/Mantis/blob/main/mantis/models/mfuyu/utils.py](url)
[https://github.com/TIGER-AI-Lab/Mantis/blob/main/mantis/models/mllava/utils.py](url)

**Comment by junming-yang** [comment]
I have tried to test following this instruction. Mantis-8B-Idefics2 can output the right answer but fails in VLMEvalKit. Mantis-8B-Fuyu can not output the right answer in the demo with transformers==4.43.0.

**Comment by junming-yang** [comment]
> You can refer to these two codes for reconstruction, or I will update and test them after a while. [https://github.com/TIGER-AI-Lab/Mantis/blob/main/mantis/models/mfuyu/utils.py](url) [https://github.com/TIGER-AI-Lab/Mantis/blob/main/mantis/models/mllava/utils.py](url)

I have fix Mantis-8B-Idefics2 in [PR366](https://github.com/open-compass/VLMEvalKit/pull/366). But I still meet some problem in  Mantis-8B-Fuyu by following the instruction https://github.com/TIGER-AI-Lab/Mantis/blob/main/examples/run_mantis_fuyu.py.

**Pull request merged**
