### PR TITLE
[Benchmark] Support TaskMeAnything-v1-imageqa-random dataset

### PR DESCRIPTION
**Pull request by weikaih04**
Hi, I add [TaskMeAnything-v1-imageqa-random dataset](https://huggingface.co/datasets/weikaih/TaskMeAnything-v1-imageqa-random/blob/main/TaskMeAnything-v1-imageqa-random.tsv). Which contains 5,700 Image QA multiple Choice Questions across 19 categories. 

Here is the repo link of [TaskMeAnything](https://github.com/JieyuZ2/TaskMeAnything/tree/main)

### CODE REVIEW

**Comment by junming-yang** [comment]
Hi, @weikaih04. We tested it but failed. The index in the file is `num-num` format. But in `image_base.py` line 66, we build the index into the int format. It will cause an error.

**Comment by junming-yang** [comment]
Has the md5 of the tsv file been changed?

**Comment by weikaih04** [comment]
```
# get md5
import hashlib

def calculate_md5(file_path):
    hash_md5 = hashlib.md5()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hash_md5.update(chunk)
    return hash_md5.hexdigest()

file_path = "/home/murphy/data-ssd/weikai/taskverse/add_tma_to_vlmevalkit/turn_tma_to_tsv/TaskMeAnything-v1-imageqa-random.tsv"
md5_hash = calculate_md5(file_path)
print(f"The MD5 hash of the file is: {md5_hash}")
```

I use this code snippet above to compute the MD5 hash. I think it is still ‘14cce4225839c4b2dbc68cee86f173d7’. Do you use the same method to compute it, If not could you provide your code snippet for computing?

> Has the md5 of the tsv file been changed? Whether `93b7290b447ef947f3b3abae5ad4bc1b` is correct?

**Comment by junming-yang** [comment]
We use the `md5` function in VLMEvalKit/vlmeval/smp/file.py.
```
def md5(s):
    hash = hashlib.new('md5')
    if osp.exists(s):
        with open(s, 'rb') as f:
            for chunk in iter(lambda: f.read(2**20), b''):
                hash.update(chunk)
    else:
        hash.update(s.encode('utf-8'))
    return str(hash.hexdigest())
```

**Comment by junming-yang** [comment]
> ```
> # get md5
> import hashlib
> 
> def calculate_md5(file_path):
>     hash_md5 = hashlib.md5()
>     with open(file_path, "rb") as f:
>         for chunk in iter(lambda: f.read(4096), b""):
>             hash_md5.update(chunk)
>     return hash_md5.hexdigest()
> 
> file_path = "/home/murphy/data-ssd/weikai/taskverse/add_tma_to_vlmevalkit/turn_tma_to_tsv/TaskMeAnything-v1-imageqa-random.tsv"
> md5_hash = calculate_md5(file_path)
> print(f"The MD5 hash of the file is: {md5_hash}")
> ```
> 
> I use this code snippet above to compute the MD5 hash. I think it is still ‘14cce4225839c4b2dbc68cee86f173d7’. Do you use the same method to compute it, If not could you provide your code snippet for computing?
> 
> > Has the md5 of the tsv file been changed? Whether `93b7290b447ef947f3b3abae5ad4bc1b` is correct?

I run with the same code. The output is 93b7290b447ef947f3b3abae5ad4bc1b.

**Comment by weikaih04** [comment]
Then It might have been a mistake on my part. I ran it today, and the result is indeed 93b7290b447ef947f3b3abae5ad4bc1b. I’ve replaced it and committed a new version.

**Pull request merged**
