### PR TITLE
[Improvement] Align evaluation results with paper

### PR DESCRIPTION
**Pull request by white2018**
The current verison of minimonkey.py evaluates model with different results compared to paper's evaluation.  The paper's link refers to https://arxiv.org/pdf/2408.02034

### CODE REVIEW

**Comment by kennymckormick** [comment]
Will re-evaluate w. this piece of codes to see if results improve

**Comment by white2018** [comment]
Thanks a lot!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-compass/VLMEvalKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月1日(星期五) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-compass/VLMEvalKit] [Improvement] Align evaluation results with paper (PR #563)





 
Will re-evaluate w. this piece of codes to see if results improve

**Comment by kennymckormick** [comment]
> Thanks a lot!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "open-compass/VLMEvalKit" ***@***.***&gt;; 发送时间:&nbsp;2024年11月1日(星期五) 下午5:20 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [open-compass/VLMEvalKit] [Improvement] Align evaluation results with paper (PR #563) Will re-evaluate w. this piece of codes to see if results improve — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Can you confirm that the modified codes run well on benchmarks we supported, at least for the 8 benchmarks on our main leaderboard? I ran MiniMonkey on MMMU_DEV_VAL with 80G A800 and the OOM error occurs. 

image

**Comment by white2018** [comment]
> > Thanks a lot!
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "open-compass/VLMEvalKit" _**@**_._**>; 发送时间: 2024年11月1日(星期五) 下午5:20 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [open-compass/VLMEvalKit] [Improvement] Align evaluation results with paper (PR #563) Will re-evaluate w. this piece of codes to see if results improve — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> Can you confirm that the modified codes run well on benchmarks we supported, at least for the 8 benchmarks on our main leaderboard? I ran MiniMonkey on MMMU_DEV_VAL with 80G A800 and the OOM error occurs.
> 
> image

I will re-evaluate MMMU_DEV_VAL dataset to see what happens. Thanks

**Comment by kennymckormick** [comment]
The evaluation results are updated.

**Pull request merged**
