### PR TITLE
[Benchmark] Added MMGenBench benchmark

### PR DESCRIPTION
**Pull request by lerogo**
[Benchmark] Added MMGenBench benchmark

### CODE REVIEW

**Comment by lerogo** [comment]
hey @kennymckormick do you think it's ready to merge?

**Comment by kennymckormick** [comment]
> hey @kennymckormick do you think it's ready to merge?

Please help fix the lint first

**Comment by lerogo** [comment]
> > hey @kennymckormick do you think it's ready to merge?
> 
> Please help fix the lint first

It's the prompt passed to MLLM, how to fix it?

**Comment by lerogo** [comment]
> > hey @kennymckormick do you think it's ready to merge?
> 
> Please help fix the lint first

It's done

**Comment by kennymckormick** [comment]
Hi, @lerogo , 
I didn't find any documents  / descriptions about the MMGenBench you contributed on the Internet. Please add some introductions to the  benchmark somewhere. If the benchmark is just for your personal use, you can also keep it in your own fork (no need to create a PR).

**Comment by lerogo** [comment]
> Hi, @lerogo , I didn't find any documents / descriptions about the MMGenBench you contributed on the Internet. Please add some introductions to the benchmark somewhere. If the benchmark is just for your personal use, you can also keep it in your own fork (no need to create a PR).

We are sorry, we are working as quickly as possible to perfect our code and documentation. Below is the link to our paper: https://arxiv.org/abs/2411.14062

**Comment by kennymckormick** [comment]
> > Hi, @lerogo , I didn't find any documents / descriptions about the MMGenBench you contributed on the Internet. Please add some introductions to the benchmark somewhere. If the benchmark is just for your personal use, you can also keep it in your own fork (no need to create a PR).
> 
> We are sorry, we are working as quickly as possible to perfect our code and documentation. Below is the link to our paper: https://arxiv.org/abs/2411.14062

Cool, will try to run the evaluation and then merge it.

**Comment by lerogo** [comment]
Thanks! I've uploaded the code. Is it possible to add a link to our benchmark inside the VLMEvalKit homepage? 

https://mmgenbench.alsoai.com/

**Review by kennymckormick — APPROVED** [review]

**Comment by kennymckormick** [comment]
> Thanks! I've uploaded the code. Is it possible to add a link to our benchmark inside the VLMEvalKit homepage?
> 
> https://mmgenbench.alsoai.com/

Added a new line in the news section.

**Comment by lerogo** [comment]
dd

**Pull request merged**
